name: "Close Issue"
author: "Kungfu Trader"
description: "Close Issue When Merged"
inputs:
  approve-token:
    description: "secrets.GITHUB_TOKEN"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
